# Generated by Django 6.1.1 on 2026-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('suscripcion', 'Suscripción'), ('donacion', 'Donación')], default='suscripcion', max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'Gratis'), ('premium', 'Pro')], help_text='Vacío si es una donación -- no está ligada a ningún plan.', max_length=10),
        ),
    ]
