# Generated by Django 6.1.1 on 2026-10-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_condominio_activo_alter_condominio_es_fundador_and_more'),
        ('pagos', '0002_pago_tipo_alter_pago_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='membresia',
            field=models.ForeignKey(blank=True, help_text='Quién donó (torre/unidad incluida) -- vacío en pagos de suscripción, que son del condominio como tal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='core.membresia'),
        ),
    ]
