# Generated by Django 6.1.1 on 2026-09-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Interruptor manual: desactivarlo bloquea todo, sin relación con el pago.')),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('premium', 'Pro')], default='premium', max_length=10)),
                ('pagado_hasta', models.DateField(blank=True, help_text='Fecha hasta la que el condominio tiene acceso pagado. Vacío = sin restricción.', null=True)),
                ('es_fundador', models.BooleanField(default=False, help_text='Uno de los primeros condominios en registrarse: precio fijo de por vida.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='core.condominio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Número o identificador del departamento/casa, ej. '304' o 'Casa 12'.", max_length=20)),
                ('alicuota', models.DecimalField(decimal_places=4, default=0, help_text='Coeficiente de copropiedad usado para prorratear gastos comunes (0 si no se usa).', max_digits=6)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.condominio')),
                ('torre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='core.torre')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('directiva', 'Directiva'), ('conserje', 'Conserjería'), ('residente', 'Residente')], default='residente', max_length=10)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='core.condominio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, help_text='Solo aplica a residentes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias', to='core.unidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('condominio', 'numero'), name='unidad_numero_unico_por_condominio'),
        ),
    ]
