# Generated by Django 6.1.1 on 2026-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unidad',
            name='unidad_numero_unico_por_condominio',
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('condominio', 'torre', 'numero'), name='unidad_numero_unico_por_torre'),
        ),
    ]
