# Generated by Django 6.1.1 on 2026-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_unidad_unidad_numero_unico_por_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='datos_transferencia',
            field=models.TextField(blank=True, help_text='Banco, tipo de cuenta, número, RUT y email de la administración — se muestra a los residentes para que paguen los gastos comunes por transferencia (no es un pago online).'),
        ),
    ]
