# Generated by Django 6.1.1 on 2026-10-07 22:39

import core.usuarios
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_condominio_datos_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=core.usuarios.generar_codigo_invitacion, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_invitacion', to='core.condominio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
