# Generated by Django 6.1.1 on 2026-10-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_codigoinvitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('condominio', models.CharField(max_length=150, verbose_name='Condominio o junta de vecinos')),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mensaje', models.TextField(blank=True)),
                ('atendido', models.BooleanField(default=False, help_text='Marca cuando ya contactaste a esta persona.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
