# Generated by Django 6.1.1 on 2026-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_condominio_token_registro_residentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='rol',
            field=models.CharField(choices=[('directiva', 'Directiva'), ('administracion', 'Administración'), ('conserje', 'Conserjería'), ('residente', 'Residente')], default='residente', max_length=15),
        ),
    ]
