# Generated by Django 6.1.1 on 2026-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membresia_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Interruptor manual: desactivarlo bloquea todo (ej. un cliente que dejó de serlo).'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='es_fundador',
            field=models.BooleanField(default=False, help_text='Uno de los primeros condominios en registrarse.'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='pagado_hasta',
            field=models.DateField(blank=True, help_text='Histórico de cuando Condofy todavía cobraba suscripción. Ya no restringe el acceso.', null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Pro')], default='premium', help_text='Condofy es gratis para todos -- este campo es solo registro interno de DevQuad, no limita nada.', max_length=10),
        ),
    ]
