# Generated by Django 6.1.1 on 2026-10-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_condominio_activo_alter_condominio_es_fundador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para residentes. No aplica a directiva/administración/conserjería.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias', to='core.unidad'),
        ),
    ]
