# Generated by Django 6.1.1 on 2026-10-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membresia_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='terminos_aceptados_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo esta persona aceptó los Términos de Uso y la Política de Privacidad. Vacío = todavía no los ha aceptado.', null=True),
        ),
        migrations.CreateModel(
            name='SolicitudEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('condominio_nombre', models.CharField(max_length=150)),
                ('motivo', models.TextField(blank=True)),
                ('atendida', models.BooleanField(default=False, help_text='Marca cuando ya se procesó la eliminación.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('membresia', models.ForeignKey(blank=True, help_text='Puede quedar vacío si la cuenta ya fue eliminada -- los campos de abajo son una copia al momento del pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_eliminacion', to='core.membresia')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
