# Generated by Django 6.1.1 on 2026-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membresia_terminos_aceptados_en_solicitudeliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='etiqueta_torre',
            field=models.CharField(default='Torre', help_text="Cómo le dicen en este condominio a la agrupación de unidades (Torre, Block, Edificio, Pabellón...) -- se usa tal cual en el panel, en vez de 'Torre' a secas.", max_length=30),
        ),
    ]
