# Generated by Django 6.1.1 on 2026-10-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_condominio_etiqueta_torre'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='etiqueta_unidad',
            field=models.CharField(default='Unidad', help_text="Cómo le dicen en este condominio a cada unidad (Unidad, Departamento, Casa...) -- se usa tal cual en el panel, en vez de 'Unidad'/'Depto' a secas.", max_length=30),
        ),
        migrations.AddField(
            model_name='condominio',
            name='genero_unidad',
            field=models.CharField(choices=[('f', 'Femenino (la/una/nueva unidad)'), ('m', 'Masculino (el/un/nuevo departamento)')], default='f', help_text="Solo para que el texto concuerde en género con etiqueta_unidad (ej. 'nueva unidad' vs 'nuevo departamento'). No afecta nada más.", max_length=1),
        ),
    ]
