# Generated by Django 6.1.1 on 2026-10-09 13:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_condominio_etiqueta_unidad_condominio_genero_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='pagado_hasta',
            field=models.DateField(blank=True, default=core.models._pagado_hasta_prueba_gratis, help_text='Hasta cuándo puede generar gastos comunes/personal nuevos sin pagar (ver SuscripcionActivaMixin) -- 20 días de prueba gratis al crear el condominio, después hay que pagar la suscripción. El resto de la app (alertas, avisos, accesos) nunca depende de este campo.', null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Pro')], default='premium', help_text='Legado -- hoy el precio es fijo ($19.990/mes, ver README), este campo es solo registro interno de DevQuad y no limita nada.', max_length=10),
        ),
    ]
