# Generated by Django 6.1.1 on 2026-09-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('robo', 'Robo'), ('incendio', 'Incendio'), ('accidente', 'Accidente'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('falsa_alarma', 'Falsa alarma')], default='activa', max_length=15)),
                ('mensaje', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_creadas', to='core.membresia')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.condominio')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to='core.membresia')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
