# Generated by Django 6.1.1 on 2026-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('falsa_alarma', 'Falsa alarma'), ('auto_cerrada', 'Cerrada automáticamente')], default='activa', max_length=15),
        ),
    ]
