# Generated by Django 6.1.1 on 2026-09-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=150)),
                ('motivo', models.CharField(choices=[('visita', 'Visita'), ('delivery', 'Delivery'), ('proveedor', 'Proveedor/servicio'), ('otro', 'Otro')], default='visita', max_length=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_hechos', to='core.membresia')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ingreso', to='core.unidad')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
