# Generated by Django 6.1.1 on 2026-10-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_condominio_etiqueta_unidad_condominio_genero_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tasa_total_pct', models.DecimalField(decimal_places=2, help_text='Cotización obligatoria (10%) + comisión de la AFP, ej. 11.44 para 11,44%.', max_digits=5)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text="Ej. '2026-10'.", max_length=20, unique=True)),
                ('valor_utm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_minimo_mensual', models.PositiveIntegerField(help_text='En pesos chilenos -- sin centavos.')),
                ('tope_imponible_uf', models.DecimalField(decimal_places=2, help_text='Tope imponible para AFP/salud/cesantía, en UF.', max_digits=6)),
                ('tasa_cesantia_trabajador_indefinido_pct', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('tasa_cesantia_trabajador_plazo_fijo_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Parámetros del periodo',
                'verbose_name_plural': 'Parámetros por periodo',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='TramoImpuestoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_utm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hasta_utm', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = tramo superior, sin techo.', max_digits=8, null=True)),
                ('tasa_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rebaja_utm', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tramo de impuesto único',
                'verbose_name_plural': 'Tramos de impuesto único',
                'ordering': ['desde_utm'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12)),
                ('cargo', models.CharField(help_text="Ej. 'Conserje', 'Aseo', 'Mantención'.", max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo fijo')], default='indefinido', max_length=12)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('sistema_salud', models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre')], default='fonasa', max_length=10)),
                ('plan_isapre_uf', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el sistema de salud es Isapre -- valor del plan en UF.', max_digits=6, null=True)),
                ('sueldo_base', models.PositiveIntegerField(help_text='En pesos chilenos -- sin centavos.')),
                ('asignacion_colacion', models.PositiveIntegerField(default=0, help_text='No imponible. En pesos chilenos -- sin centavos.')),
                ('asignacion_movilizacion', models.PositiveIntegerField(default=0, help_text='No imponible. En pesos chilenos -- sin centavos.')),
                ('aplica_gratificacion', models.BooleanField(default=False, help_text='Activar solo si un contador confirmó que el condominio está obligado a pagar gratificación legal.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='personal.afp')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.condominio')),
                ('membresia', models.OneToOneField(blank=True, help_text='Si además tiene cuenta de conserjería en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to='core.membresia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text="Ej. '2026-10'.", max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('sueldo_base', models.PositiveIntegerField()),
                ('gratificacion', models.PositiveIntegerField(default=0)),
                ('asignacion_colacion', models.PositiveIntegerField(default=0)),
                ('asignacion_movilizacion', models.PositiveIntegerField(default=0)),
                ('total_imponible', models.PositiveIntegerField()),
                ('total_haberes', models.PositiveIntegerField()),
                ('descuento_afp', models.PositiveIntegerField()),
                ('descuento_salud', models.PositiveIntegerField()),
                ('descuento_cesantia', models.PositiveIntegerField()),
                ('impuesto_unico', models.PositiveIntegerField()),
                ('total_descuentos', models.PositiveIntegerField()),
                ('liquido_a_pagar', models.PositiveIntegerField()),
                ('utm_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp_nombre_usada', models.CharField(max_length=50)),
                ('afp_tasa_usada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='personal.empleado')),
            ],
            options={
                'ordering': ['-periodo'],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'periodo'), name='liquidacion_unica_por_empleado_y_periodo')],
            },
        ),
    ]
