# Generated by Django 6.1.1 on 2026-10-09 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosperiodo',
            name='tope_imponible_uf',
        ),
        migrations.AddField(
            model_name='parametrosperiodo',
            name='tope_imponible_afp_salud_uf',
            field=models.DecimalField(decimal_places=2, default=90, help_text='Tope imponible para AFP y salud, en UF (distinto del de cesantía).', max_digits=6),
        ),
        migrations.AddField(
            model_name='parametrosperiodo',
            name='tope_imponible_cesantia_uf',
            field=models.DecimalField(decimal_places=2, default=Decimal('135.2'), help_text='Tope imponible para el seguro de cesantía, en UF (más alto que el de AFP/salud).', max_digits=6),
        ),
    ]
