# Generated by Django 6.1.1 on 2026-09-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.membresia')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.condominio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
