# Generated by Django 6.1.1 on 2026-09-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text="Ej. '2026-09'.", max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_comunes', to='core.condominio')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CuotaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.unidad')),
                ('gasto_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gastoscomunes.gastocomun')),
            ],
            options={
                'ordering': ['unidad__numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='gastocomun',
            constraint=models.UniqueConstraint(fields=('condominio', 'periodo'), name='gastocomun_periodo_unico_por_condominio'),
        ),
        migrations.AddConstraint(
            model_name='cuotaunidad',
            constraint=models.UniqueConstraint(fields=('gasto_comun', 'unidad'), name='cuota_unica_por_gasto_y_unidad'),
        ),
    ]
