# Generated by Django 6.1.1 on 2026-10-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscomunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocomun',
            name='monto_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si el cargo es una cuota fija por unidad (no prorrateada por alícuota), queda el valor acá y en monto_total queda el total resultante.', max_digits=12, null=True),
        ),
    ]
