# Generated by Django 6.1.1 on 2026-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscomunes', '0002_gastocomun_monto_por_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaunidad',
            name='monto',
            field=models.PositiveIntegerField(help_text='En pesos chilenos -- sin centavos.'),
        ),
        migrations.AlterField(
            model_name='gastocomun',
            name='monto_por_unidad',
            field=models.PositiveIntegerField(blank=True, help_text='Si el cargo es una cuota fija por unidad (no prorrateada por alícuota), queda el valor acá y en monto_total queda el total resultante.', null=True),
        ),
        migrations.AlterField(
            model_name='gastocomun',
            name='monto_total',
            field=models.PositiveIntegerField(help_text='En pesos chilenos -- sin centavos.'),
        ),
    ]
