# Generated by Django 6.1.1 on 2026-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscomunes', '0003_alter_cuotaunidad_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocomun',
            name='es_voluntario',
            field=models.BooleanField(default=False, help_text='Aporte voluntario (ej. recaudar para un proyecto puntual) -- cada unidad dona lo que quiera, no genera morosidad ni monto obligatorio.'),
        ),
    ]
